"""Actionable explanations shared by every calculation entry point."""

# title, why, next step, destination
GUIDANCE = {
    'purpose': ('Mi a vizsgálat célja?', 'A következtetés alkalmazhatósága a vizsgálat céljától függ.', 'Az Ügyadatokban írd le, milyen döntéshez vagy eljáráshoz készül a vizsgálat.', 'settings'),
    'history_date': ('Melyik időpontra szólt a korábbi minősítés?', 'Az előzménynek meg kell előznie a legelső vizsgált évet.', 'Add meg a korábbi minősítés referenciaidejét az Ügyadatokban.', 'settings'),
    'history_unknown': ('További előzmény szükséges', 'A rendelkezésre álló évek nem igazolják a kétéves szabály szerinti kategóriát.', 'Rögzíts igazolt korábbi minősítést és dátumot, vagy vegyél fel további korábbi évet a beszámolóival és árfolyamával.', 'settings'),
    'event': ('Hogyan hatott a strukturális változás?', 'Az esemény módosíthatja a hálót és a történeti minősítést.', 'Indokold az esemény minősítésre gyakorolt hatását, majd jelöld szakértőileg ellenőrzöttnek.', 'event'),
    'future_period': ('Az üzleti év még nem zárult le', 'A vizsgálat napján még nem lezárt év nem kezelhető elfogadott beszámolóként.', 'Ellenőrizd a vizsgálat napját és a vizsgált éveket. Új vállalkozásnál a dokumentált évesített becslés külön rögzíthető.', 'settings'),
    'rate_missing': ('Hiányzik az éves árfolyam', 'A pénzügyi mérethatárok EUR-ban vannak meghatározva.', 'Az adott év Árfolyam paneljén add meg az érvényesség és jegyzés napját, HUF/EUR értéket, forrást és az ellenőrzést.', 'rate'),
    'rate_unconfirmed': ('Az árfolyam még nincs igazolva', 'A beírt szám önmagában nem igazolja a hivatalos árfolyamot.', 'Rögzíts hivatalos forrást, ellenőrizd a dátumot és az értéket, majd pipáld ki az árfolyam ellenőrzését.', 'rate'),
    'rate_date': ('Más napra szól az árfolyam', 'A releváns zárónapra, becslésnél az előző év végére érvényes érték kell.', 'Állítsd az érvényesség napját az üzenetben megadott dátumra, és ellenőrizd újra az értéket.', 'rate'),
    'rate_quoted': ('A jegyzés napja nem megfelelő', 'A jegyzés nem lehet későbbi az érvényességnél vagy tíz napnál korábbi.', 'Válaszd az érvényesség napján vagy az azt megelőző tíz napban elérhető legutolsó hivatalos EUR-jegyzést.', 'rate'),
    'root_inactive': ('A vizsgált cég nem aktív a háló napján', 'Az alapítás vagy megszűnés dátuma kizárja a vállalkozást a kiválasztott időpontban.', 'Ellenőrizd a vizsgált cég alapítását, megszűnését és az Ügyadatok cégháló-időpontját.', 'company'),
    'ownership_source': ('Mivel igazolható a tulajdoni kapcsolat?', 'A számításnak visszakövethető tulajdoni és szavazati tényekre kell épülnie.', 'Add meg ennél a kapcsolatnál az igazoló forrást: például cégkivonat, társasági szerződés vagy nyilatkozat.', 'ownership'),
    'control_reason': ('Milyen jog biztosítja az irányítást?', 'A megjelölt irányítási jog a százaléktól függetlenül kapcsolódást eredményezhet.', 'Írd le az irányítás jogcímét, például kinevezési jogot vagy szerződéses meghatározó befolyást, és a forrását.', 'ownership'),
    'investor_reason': ('Miért alkalmazható a befektetői kivétel?', 'A kivétel megváltoztatja a partnerküszöb alkalmazását.', 'A vállalkozás adatlapján indokold és igazold a kivételt; ha nem alkalmazható, vedd ki a jelölést.', 'company'),
    'ownership_sum': ('A rögzített arányok meghaladják a 100%-ot', 'Ugyanarra az időpontra nem adható 100%-nál több tőke vagy szavazat.', 'Nézd át az érintett cég tulajdonosainak arányait és érvényességi időszakait. Javítsd az átfedést vagy az arányt.', 'graph'),
    'decision_review': ('A kapcsolati döntés még nincs ellenőrizve', 'A kiválasztott minősítést indokkal és forrással is igazolni kell.', 'Pótold az üzenetben felsorolt hiányokat, és jelöld a döntést ellenőrzöttnek. A mentés önmagában nem helyettesíti az ellenőrzést.', 'decision'),
    'persons_market': ('Közös fellépés és piaci kapcsolat szükséges', 'Természetes személyeken keresztüli kapcsolódáshoz a rokonság önmagában nem elegendő.', 'Írd le a közös fellépés tényállását és az azonos vagy szomszédos piac indokát. A megállapítást forrással támaszd alá.', 'decision'),
    'relation_unresolved': ('Milyen kapcsolat van a két cég között?', 'A „Tisztázandó” választás még nem döntés; a véglegesítéshez minősítés kell.', 'Válassz kapcsolódó, partner vagy önálló minősítést az igazolt tények szerint. Partnernél add meg a beszámítási arányt is.', 'decision'),
    'relationship_missing': ('Nem állapítható meg a cég kapcsolata', 'Nincs rögzített vállalkozási tulajdoni kapcsolat vagy szakértői döntés, amely rendezné a cég helyzetét. Személyi tulajdon és rokonság önmagában nem dönti el a beszámítást.', 'Rögzíts tulajdoni/szavazati kapcsolatot, vagy hozz indokolt döntést a vizsgált céggel: kapcsolódó (100%), partner (megadott arány), vagy önálló (0%). Add meg a forrást és ellenőrizd a döntést.', 'new_decision'),
    'partner_conflict': ('Eltérő arányok ugyanahhoz a cégpárhoz', 'Az egymásnak ellentmondó partnerarányokból nem választható önkényesen.', 'Egyeztesd a cégpár tulajdoni adatait és szakértői partnerdöntéseit a kiválasztott év hálóidőpontjában.', 'decisions'),
    'override_conflict': ('Több felülbírálat ugyanarra az adatblokkra', 'A kapcsolódó blokk minden cégét azonos végső aránnyal kell kezelni.', 'Az adott év és adatblokk felülbírálatai közül csak egy indokolt végső arány maradjon.', 'decisions'),
    'override_review': ('A végső beszámítási arány nincs ellenőrizve', 'A kézzel meghatározott arány szakértői megerősítést igényel.', 'Ellenőrizd az összeszámítási döntés arányát és indokát, majd jelöld ellenőrzöttnek.', 'override'),
    'multiple_paths': ('Több útvonalon érhető el a partnerblokk', 'Több partnerkapcsolatból nem állapítható meg automatikusan a végső arány.', 'Hozz az adott évre összeszámítási döntést a megjelölt adatblokkra: végső százalék, indoklás és szakértői ellenőrzés.', 'override'),
    'independent_conflict': ('Az önálló döntés ellentmond a hálónak', 'Igazolt kapcsolódási lánc vagy releváns partnerarány mellett a cég nem zárható ki indok nélkül.', 'Egyeztesd a döntést a tulajdoni/irányítási kapcsolatokkal. Javítsd a téves minősítést vagy a hibás alapadatot.', 'decision'),
    'financial_missing': ('Hiányoznak a beszámoló számai', 'A hiányzó adat nem nulla; a beszámítandó cég mutatói nélkül az összegzés hiányos.', 'Az adott évben töltsd ki a létszámot, árbevételt és mérlegfőösszeget. A pénzügyi mezők ezer HUF vagy ezer EUR egységűek.', 'financials'),
    'financial_source': ('Mi a beszámolóadat forrása?', 'A beszámoló számainak visszakövethetőknek kell lenniük.', 'Add meg a beszámoló vagy igazoló dokumentum megnevezését az Adatforrás mezőben.', 'financial'),
    'financial_period': ('Melyik időszakot fedi a beszámoló?', 'Az időszak nélkül nem ellenőrizhető a beszámolók összehasonlíthatósága.', 'A beszámoló részleteiben add meg az időszak kezdetét és végét.', 'financial'),
    'financial_acceptance': ('Mikor fogadták el a beszámolót?', 'A vizsgálat napján már rendelkezésre álló, elfogadott beszámoló kell.', 'Add meg az elfogadás napját; az nem lehet későbbi a vizsgálat időpontjánál.', 'financial'),
    'estimate': ('Az évesített becslés igazolása hiányzik', 'Új vállalkozás becslésének módszerét dokumentálni kell.', 'Indokold az évesítést az adatforrásban, és jelöld, hogy az évesítést elvégeztétek.', 'financial'),
    'short_year': ('Rövid beszámolási időszak', 'A rövid időszak adatai évesítés nélkül nem összehasonlíthatók.', 'Ellenőrizd az időszakot, dokumentáld az évesítést, és jelöld annak elvégzését.', 'financial'),
    'employment_method': ('EU-profilhoz AWU-létszám kell', 'Az EU-profil éves munkaegységet használ a létszámhoz.', 'Rögzíts AWU szerint mért létszámot, válaszd az AWU módszert, és add meg a forrást.', 'financial'),
    'period_alignment': ('Eltérő üzletiév-zárás', 'Az összesített adatoknak a vizsgált cég időszakához kell igazodniuk.', 'Egyeztesd a cég beszámolási időszakát a vizsgált cég zárónapjával, és rögzíts megfelelő forrásadatot.', 'financial'),
    'consolidation_weight': ('Eltérő arányú cégek konszolidált adatban', 'Az eltérő súlyú adatokat egyetlen konszolidált számból nem lehet helyesen súlyozni.', 'Rendezd a konszolidált adat körét vagy adj meg megfelelő egyedi forrásadatokat. Ne töröld indok nélkül a bevont cégeket.', 'financial'),
    'consolidation_overlap': ('Átfedő konszolidált beszámolók', 'Ugyanaz a cégadat nem számítható be kétszer.', 'Egyeztesd a konszolidált beszámolókba bevont cégeket és a forrásadatokat.', 'financial'),
    'public_review': ('Közjogi részesedés összesítése szükséges', 'A közvetlen és közvetett állami/önkormányzati arány a KKV-státuszt is érintheti.', 'Add meg a teljes közjogi tőke- és szavazati arányt, indokold forrással, majd ellenőrizd az összesítést.', 'public'),
    'public_conflict': ('Az összesítés kisebb a közvetlen aránynál', 'A teljes közjogi arány nem lehet kisebb az igazolt közvetlen részesedésnél.', 'Egyeztesd az összesített arányokat a közjogi tulajdonosok rögzített közvetlen kapcsolataival.', 'public'),
    'public_exception': ('A közjogi kivétel nincs igazolva', 'A kivétel felülírhatja a közjogi kizárást, ezért indokolni és ellenőrizni kell.', 'Igazold az adott jogi profil szerinti kivételt, vagy vedd ki a kivétel jelölését.', 'public'),
    'post_event_structure': ('A változás utáni háló szükséges', 'Azonnali strukturális hatásnál a korábbi zárónapi háló már nem megfelelő.', 'Az Ügyadatokban válaszd a vizsgálati napi céghálót, és rendezd a változás utáni adatokat.', 'settings'),
}


def explanation(code):
    title, why, action, destination = GUIDANCE[code]
    return {'title': title, 'why': why, 'action': action, 'destination': destination}
